# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/opensource/github/cooleader320/cpp_cross_demo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/opensource/github/cooleader320/cpp_cross_demo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/opensource/github/cooleader320/cpp_cross_demo/CMakeFiles /mnt/d/opensource/github/cooleader320/cpp_cross_demo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/opensource/github/cooleader320/cpp_cross_demo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named math_static

# Build rule for target.
math_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 math_static
.PHONY : math_static

# fast build rule for target.
math_static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_static.dir/build.make CMakeFiles/math_static.dir/build
.PHONY : math_static/fast

#=============================================================================
# Target rules for targets named math_shared

# Build rule for target.
math_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 math_shared
.PHONY : math_shared

# fast build rule for target.
math_shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_shared.dir/build.make CMakeFiles/math_shared.dir/build
.PHONY : math_shared/fast

#=============================================================================
# Target rules for targets named app_static

# Build rule for target.
app_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app_static
.PHONY : app_static

# fast build rule for target.
app_static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_static.dir/build.make CMakeFiles/app_static.dir/build
.PHONY : app_static/fast

#=============================================================================
# Target rules for targets named app_shared

# Build rule for target.
app_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app_shared
.PHONY : app_shared

# fast build rule for target.
app_shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_shared.dir/build.make CMakeFiles/app_shared.dir/build
.PHONY : app_shared/fast

#=============================================================================
# Target rules for targets named run_app_static

# Build rule for target.
run_app_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_app_static
.PHONY : run_app_static

# fast build rule for target.
run_app_static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_app_static.dir/build.make CMakeFiles/run_app_static.dir/build
.PHONY : run_app_static/fast

#=============================================================================
# Target rules for targets named run_app_shared

# Build rule for target.
run_app_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_app_shared
.PHONY : run_app_shared

# fast build rule for target.
run_app_shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_app_shared.dir/build.make CMakeFiles/run_app_shared.dir/build
.PHONY : run_app_shared/fast

#=============================================================================
# Target rules for targets named cmake_help

# Build rule for target.
cmake_help: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cmake_help
.PHONY : cmake_help

# fast build rule for target.
cmake_help/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_help.dir/build.make CMakeFiles/cmake_help.dir/build
.PHONY : cmake_help/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_static.dir/build.make CMakeFiles/app_static.dir/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_shared.dir/build.make CMakeFiles/app_shared.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_static.dir/build.make CMakeFiles/app_static.dir/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_shared.dir/build.make CMakeFiles/app_shared.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_static.dir/build.make CMakeFiles/app_static.dir/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_shared.dir/build.make CMakeFiles/app_shared.dir/main.cpp.s
.PHONY : main.cpp.s

src/math.o: src/math.cpp.o
.PHONY : src/math.o

# target to build an object file
src/math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_static.dir/build.make CMakeFiles/math_static.dir/src/math.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_shared.dir/build.make CMakeFiles/math_shared.dir/src/math.cpp.o
.PHONY : src/math.cpp.o

src/math.i: src/math.cpp.i
.PHONY : src/math.i

# target to preprocess a source file
src/math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_static.dir/build.make CMakeFiles/math_static.dir/src/math.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_shared.dir/build.make CMakeFiles/math_shared.dir/src/math.cpp.i
.PHONY : src/math.cpp.i

src/math.s: src/math.cpp.s
.PHONY : src/math.s

# target to generate assembly for a file
src/math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_static.dir/build.make CMakeFiles/math_static.dir/src/math.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_shared.dir/build.make CMakeFiles/math_shared.dir/src/math.cpp.s
.PHONY : src/math.cpp.s

src/math_jni.o: src/math_jni.cpp.o
.PHONY : src/math_jni.o

# target to build an object file
src/math_jni.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_static.dir/build.make CMakeFiles/math_static.dir/src/math_jni.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_shared.dir/build.make CMakeFiles/math_shared.dir/src/math_jni.cpp.o
.PHONY : src/math_jni.cpp.o

src/math_jni.i: src/math_jni.cpp.i
.PHONY : src/math_jni.i

# target to preprocess a source file
src/math_jni.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_static.dir/build.make CMakeFiles/math_static.dir/src/math_jni.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_shared.dir/build.make CMakeFiles/math_shared.dir/src/math_jni.cpp.i
.PHONY : src/math_jni.cpp.i

src/math_jni.s: src/math_jni.cpp.s
.PHONY : src/math_jni.s

# target to generate assembly for a file
src/math_jni.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_static.dir/build.make CMakeFiles/math_static.dir/src/math_jni.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_shared.dir/build.make CMakeFiles/math_shared.dir/src/math_jni.cpp.s
.PHONY : src/math_jni.cpp.s

src/math_rsa.o: src/math_rsa.cpp.o
.PHONY : src/math_rsa.o

# target to build an object file
src/math_rsa.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_static.dir/build.make CMakeFiles/math_static.dir/src/math_rsa.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_shared.dir/build.make CMakeFiles/math_shared.dir/src/math_rsa.cpp.o
.PHONY : src/math_rsa.cpp.o

src/math_rsa.i: src/math_rsa.cpp.i
.PHONY : src/math_rsa.i

# target to preprocess a source file
src/math_rsa.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_static.dir/build.make CMakeFiles/math_static.dir/src/math_rsa.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_shared.dir/build.make CMakeFiles/math_shared.dir/src/math_rsa.cpp.i
.PHONY : src/math_rsa.cpp.i

src/math_rsa.s: src/math_rsa.cpp.s
.PHONY : src/math_rsa.s

# target to generate assembly for a file
src/math_rsa.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_static.dir/build.make CMakeFiles/math_static.dir/src/math_rsa.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math_shared.dir/build.make CMakeFiles/math_shared.dir/src/math_rsa.cpp.s
.PHONY : src/math_rsa.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... cmake_help"
	@echo "... run_app_shared"
	@echo "... run_app_static"
	@echo "... app_shared"
	@echo "... app_static"
	@echo "... math_shared"
	@echo "... math_static"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/math.o"
	@echo "... src/math.i"
	@echo "... src/math.s"
	@echo "... src/math_jni.o"
	@echo "... src/math_jni.i"
	@echo "... src/math_jni.s"
	@echo "... src/math_rsa.o"
	@echo "... src/math_rsa.i"
	@echo "... src/math_rsa.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

